service: auth-server
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  timeout: 30 # optional, in seconds, default is 6

functions:
  getAccessToken:
    handler: handler.getAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
          cors: true

  refreshAccessToken:
    handler: handler.refreshAccessToken
    events:
      - http:
          path: api/token/{code}
          method: get
          cors: true
